// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDa15yTxnl4dVLb9oWt5WLZ57mj2cEFqI',
    appId: '1:380157849971:web:c52b009aefd8b04da95506',
    messagingSenderId: '380157849971',
    projectId: 'dog-list-9e9d2',
    authDomain: 'dog-list-9e9d2.firebaseapp.com',
    storageBucket: 'dog-list-9e9d2.appspot.com',
    measurementId: 'G-W9M8PMY0S9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLftrNrfs-66tvHXJQQxISXhZ1axvUsWI',
    appId: '1:380157849971:android:9da21dde7f4416b2a95506',
    messagingSenderId: '380157849971',
    projectId: 'dog-list-9e9d2',
    storageBucket: 'dog-list-9e9d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiApzoy-sNbyRPdWb9LT8gCnDn8FP0AFs',
    appId: '1:380157849971:ios:c04036c857a4c3c0a95506',
    messagingSenderId: '380157849971',
    projectId: 'dog-list-9e9d2',
    storageBucket: 'dog-list-9e9d2.appspot.com',
    iosClientId: '380157849971-k7kjomjld7ibue3qgj8ned1ehmf44uhu.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotifyPrototype',
  );
}
